# Generated by Django 6.0.6 on 2026-06-09 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weightconfig',
            name='invited_password',
            field=models.CharField(default='invited2024', help_text='Password required to access the Invited Evaluator form', max_length=100),
        ),
        migrations.AddField(
            model_name='weightconfig',
            name='tutor_password',
            field=models.CharField(default='tutor2024', help_text='Password required to access the Tutor evaluation form', max_length=100),
        ),
    ]
