# Generated by Django 6.0.6 on 2026-06-09 02:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0002_weightconfig_invited_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weightconfig',
            name='invited_password',
            field=models.CharField(default='invited2024', help_text='Password for Invited Evaluator form', max_length=100),
        ),
        migrations.AlterField(
            model_name='weightconfig',
            name='tutor_password',
            field=models.CharField(default='tutor2024', help_text='Password for Tutor form AND dashboard access', max_length=100),
        ),
        migrations.CreateModel(
            name='Presenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order within group')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presenters', to='evaluations.group')),
            ],
            options={
                'ordering': ['group', 'order', 'name'],
                'unique_together': {('group', 'name')},
            },
        ),
    ]
